// Autogenerated using mud system-types
export const systemToId = {
  BRCreateGameSystem: "system.BRCreateGameSystem",
  BREndGameSystem: "system.BREndGameSystem",
  BRJoinGameSystem: "system.BRJoinGameSystem",
  BRKillOutOfBoundsPiecesSystem: "system.BRKillOutOfBoundsPiecesSystem",
  BRLeaveGameSystem: "system.BRLeaveGameSystem",
  BRMovePieceSystem: "system.BRMovePieceSystem",
  BRSetPieceTypeSystem: "system.BRSetPieceTypeSystem",
  BRStartGameSystem: "system.BRStartGameSystem",
  MovePieceSystem: "system.MovePiece",
  RevokeControllerSystem: "system.RevokeController",
  SetControllerSystem: "system.SetController",
  SetPieceNameSystem: "system.SetPieceName",
  SetPieceTypeSystem: "system.SetPieceType",
  SpawnSystem: "system.Spawn",
  TransferOwnerSystem: "system.TransferOwner",
};

export const idToSystem = {
  "system.BRCreateGameSystem": "BRCreateGameSystem",
  "system.BREndGameSystem": "BREndGameSystem",
  "system.BRJoinGameSystem": "BRJoinGameSystem",
  "system.BRKillOutOfBoundsPiecesSystem": "BRKillOutOfBoundsPiecesSystem",
  "system.BRLeaveGameSystem": "BRLeaveGameSystem",
  "system.BRMovePieceSystem": "BRMovePieceSystem",
  "system.BRSetPieceTypeSystem": "BRSetPieceTypeSystem",
  "system.BRStartGameSystem": "BRStartGameSystem",
  "system.MovePiece": "MovePieceSystem",
  "system.RevokeController": "RevokeControllerSystem",
  "system.SetController": "SetControllerSystem",
  "system.SetPieceName": "SetPieceNameSystem",
  "system.SetPieceType": "SetPieceTypeSystem",
  "system.Spawn": "SpawnSystem",
  "system.TransferOwner": "TransferOwnerSystem",
};
  