// Autogenerated using mud system-types
import BRCreateGameSystem from "../abi/BRCreateGameSystem.json";
import BRJoinGameSystem from "../abi/BRJoinGameSystem.json";
import BRMovePieceSystem from "../abi/BRMovePieceSystem.json";
import BRSetPieceTypeSystem from "../abi/BRSetPieceTypeSystem.json";
import BRStartGameSystem from "../abi/BRStartGameSystem.json";
import MovePieceSystem from "../abi/MovePieceSystem.json";
import RevokeControllerSystem from "../abi/RevokeControllerSystem.json";
import SetControllerSystem from "../abi/SetControllerSystem.json";
import SetPieceTypeSystem from "../abi/SetPieceTypeSystem.json";
import SpawnSystem from "../abi/SpawnSystem.json";
import TransferOwnerSystem from "../abi/TransferOwnerSystem.json";

export const SystemAbis = {
  "system.BRCreateGameSystem": BRCreateGameSystem.abi,
  "system.BRJoinGameSystem": BRJoinGameSystem.abi,
  "system.BRMovePieceSystem": BRMovePieceSystem.abi,
  "system.BRSetPieceTypeSystem": BRSetPieceTypeSystem.abi,
  "system.BRStartGameSystem": BRStartGameSystem.abi,
  "system.MovePiece": MovePieceSystem.abi,
  "system.RevokeController": RevokeControllerSystem.abi,
  "system.SetController": SetControllerSystem.abi,
  "system.SetPieceType": SetPieceTypeSystem.abi,
  "system.Spawn": SpawnSystem.abi,
  "system.TransferOwner": TransferOwnerSystem.abi,
};
