// Autogenerated using mud system-types
import { BRCreateGameSystem } from "./ethers-contracts/BRCreateGameSystem";
import { BRJoinGameSystem } from "./ethers-contracts/BRJoinGameSystem";
import { BRMovePieceSystem } from "./ethers-contracts/BRMovePieceSystem";
import { BRSetPieceTypeSystem } from "./ethers-contracts/BRSetPieceTypeSystem";
import { BRStartGameSystem } from "./ethers-contracts/BRStartGameSystem";
import { MovePieceSystem } from "./ethers-contracts/MovePieceSystem";
import { RevokeControllerSystem } from "./ethers-contracts/RevokeControllerSystem";
import { SetControllerSystem } from "./ethers-contracts/SetControllerSystem";
import { SetPieceTypeSystem } from "./ethers-contracts/SetPieceTypeSystem";
import { SpawnSystem } from "./ethers-contracts/SpawnSystem";
import { TransferOwnerSystem } from "./ethers-contracts/TransferOwnerSystem";
 
export type SystemTypes = {
  "system.BRCreateGameSystem": BRCreateGameSystem;
  "system.BRJoinGameSystem": BRJoinGameSystem;
  "system.BRMovePieceSystem": BRMovePieceSystem;
  "system.BRSetPieceTypeSystem": BRSetPieceTypeSystem;
  "system.BRStartGameSystem": BRStartGameSystem;
  "system.MovePiece": MovePieceSystem;
  "system.RevokeController": RevokeControllerSystem;
  "system.SetController": SetControllerSystem;
  "system.SetPieceType": SetPieceTypeSystem;
  "system.Spawn": SpawnSystem;
  "system.TransferOwner": TransferOwnerSystem;
};
