export const ERROR_ABI = [
  "error BRIncorrectControllers()",
  "error BRGameNotStarted()",
  "error BREntityNotGame()",
  "error BRGameAlreadyStarted()",
  "error BRAlreadyInGame()",
  "error BRGameNotInProgress()",
  "error BRNotInGame()",
  "error BRPieceDead()",
  "error BRBeforeStartTime()",
  "error BRNotEnoughPoints()",
  "error BRNotRecharged()",
  "error BRNotRevokeSystem()",
  "error NotOwner()",
  "error NotController()",
  "error AlreadyHasController()",
  "error CannotControl()",
  "error UnimplementedPieceType()",
  "error InvalidMove()",
  "error NotPiece()",
];
