import GameProvider from "../context/GameContext";
import Head from "next/head";
import LoadingProvider from "../context/LoadingContext";
import Lobby from "../components/lobby/Lobby";
import Title from "../components/Title";

export default function Home() {
  return (
    <>
      <Head>
        <title>Ape&apos;s Gambit</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <GameProvider brGameEntity={undefined}>
          <Lobby />
          <LoadingProvider>
            <Title />
          </LoadingProvider>
        </GameProvider>
      </main>
    </>
  );
}
